# https://github.com/home-assistant/docker-base
build_from:
  aarch64: 'homeassistant/aarch64-base-debian:bullseye'
  amd64: 'homeassistant/amd64-base-debian:bullseye'
  armhf: 'homeassistant/armhf-base-debian:bullseye'
  armv7: 'homeassistant/armv7-base-debian:bullseye'
  i386: 'homeassistant/i386-base-debian:bullseye'
