FROM ghcr.io/kellerza/hass-addon-sunsynk-multi:0.8.1

# Install sunsynk from local source
COPY sunsynk sunsynk
RUN pip3 install -e ./sunsynk[pymodbus,umodbus,solarman] --no-cache-dir --disable-pip-version-check

COPY rootfs /
