# FROM ghcr.io/kellerza/hass-addon-sunsynk-multi/armhf:edge
FROM ghcr.io/kellerza/hass-addon-sunsynk-multi/armhf:0.7.5

# Install sunsynk from local source
COPY sunsynk sunsynk
RUN pip3 install -e ./sunsynk[pymodbus,umodbus,solarman] --no-cache-dir --disable-pip-version-check

COPY rootfs /
