name: Deploy sunsynk addon to ghcr.io

on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: read
    #secrets: inherit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.2

      - name: Get all test, doc and src files that have changed
        id: changed
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            sunsynk:
              - ".github/workflows/deploy-addons.yml"
              - "hass-addon-sunsynk-multi/**"
              - "hass-addon-sunsynk-edge/**"
              - "src/ha_addon_sunsynk_multi/**"
              - "src/sunsynk/**"
              - "pyproject.toml"
              - "uv.lock"

    outputs:
      changed_ss: ${{ steps.changed.outputs.sunsynk_any_changed  }}

  deployer:
    needs: [check]
    if: ${{ needs.check.outputs.changed_ss == 'true' }}
    uses: kellerza/hass-addons/.github/workflows/deployer2.yml@main
    secrets: inherit
    with:
      app: hass-addon-sunsynk-multi
      app-edge: hass-addon-sunsynk-edge
      publish: true
