name: Deploy sunsynk addon to ghcr.io

on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  deployer:
    uses: kellerza/hass-addons/.github/workflows/deployer2.yml@main
    secrets: inherit
    with:
      app: hass-addon-sunsynk-multi
      app-edge: hass-addon-sunsynk-edge
      publish: false
