name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - "www/**"
      - ".github/workflows/deploy-docs.yml"

defaults:
  run:
    working-directory: www

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18
      - run: npm ci
      - run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: www/docs/.vitepress/dist
